const actionTypes = {

  APP_LOADING: 'APP_LOADING',
  //Messages
  SEND_MESSAGE: 'SEND_MESSAGE',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  GET_ALL_MESSAGES: 'GET_ALL_MESSAGES',
  GET_MESSAGES: 'GET_MESSAGES',
  GET_MESSAGES_LOADING: 'GET_MESSAGES_LOADING',
  GET_MESSAGES_LOADED: 'GET_MESSAGES_LOADED',
  GET_MESSAGES_FAILURE: 'GET_MESSAGES_FAILURE',

  //Users
  GET_CONTACTS: 'GET_CONTACTS',
  GET_USERS: 'GET_USERS',
  GET_USER: 'GET_USER',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS ',
  GET_USER_LOADING: 'GET_USER_LOADING',
  GET_USER_FAILURE: 'GET_USER_FAILURE',
  GET_CONTACTS_SUCCESS: 'GET_CONTACTS_SUCCESS',
  GET_CHATS_LOADING: 'GET_CHATS_LOADING',
  GET_CHATS_FAILURE: 'GET_CHATS_FAILURE',
  GET_CHATS_SUCCESS: 'GET_CHATS_SUCCESS',

  //Groups
  GET_GROUPS: 'GET_GROUPS',
  GET_MY_GROUPS: 'GET_MY_GROUPS',
  GET_GROUP_MESSAGES: 'GET_GROUP_MESSAGES',
  GET_GROUPS_SUCCESS: 'GET_GROUPS_SUCCESS',
  GET_GROUPS_LOADING: 'GET_GROUPS_LOADING',
  GET_GROUPS_FAILURE: 'GET_GROUPS_FAILURE',
}
 
export default actionTypes;