const actionTypes = {

  //Messages
  SEND_MESSAGE: 'SEND_MESSAGE',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  GET_ALL_MESSAGES: 'GET_ALL_MESSAGES',
  GET_MESSAGES: 'GET_MESSAGES',

  //Users
  GET_CONTACTS: 'GET_CONTACTS',
  GET_USERS: 'GET_USERS',
  GET_USER: 'GET_USER',

  //Groups
  GET_GROUPS: 'GET_GROUPS',
  GET_MY_GROUPS: 'GET_MY_GROUPS',
  GET_GROUP_MESSAGES: 'GET_GROUP_MESSAGES',
}
 
