const actionTypes = {
  APP_LOADING: 'APP_LOADING',
  GET_CONTACTS: 'GET_CONTACTS',
  GET_USERS: 'GET_USERS',
  GET_USER: 'GET_USER',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_LOADING: 'GET_USER_LOADING',
  GET_USER_FAILURE: 'GET_USER_FAILURE',
  GET_CONTACTS_SUCCESS: 'GET_CONTACTS_SUCCESS',
  GET_CHATS_LOADING: 'GET_CHATS_LOADING',
  GET_CHATS_FAILURE: 'GET_CHATS_FAILURE',
  GET_CHATS_SUCCESS: 'GET_CHATS_SUCCESS',
  MESSAGE_SENT: 'MESSAGE_SENT',
  SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE',
  USER_CREATED: 'USER_CREATED',
  USER_CREATE_FAILED: 'USER_CREATE_FAILED',
  LOAD_MORE_CONTACTS: 'LOAD_MORE_CONTACTS',
  LOAD_MORE_CHAT: 'LOAD_MORE_CHAT',
  
}
 
export default actionTypes;