const actionTypes = {
  APP_LOADING: 'APP_LOADING',
  GET_CONTACTS: 'GET_CONTACTS',
  GET_USERS: 'GET_USERS',
  GET_USER: 'GET_USER',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_LOADING: 'GET_USER_LOADING',
  GET_USER_FAILURE: 'GET_USER_FAILURE',
  GET_CONTACTS_SUCCESS: 'GET_CONTACTS_SUCCESS',
  GET_CHATS_LOADING: 'GET_CHATS_LOADING',
  GET_CHATS_FAILURE: 'GET_CHATS_FAILURE',
  GET_CHATS_SUCCESS: 'GET_CHATS_SUCCESS',
}
 
export default actionTypes;