const actionTypes = {
  GET_GROUP_CHAT_SUCCESS: 'GET_GROUP_CHAT_SUCCESS',
  GET_GROUPS_SUCCESS: 'GET_GROUPS_SUCCESS',
  GET_GROUPS_LOADING: 'GET_GROUPS_LOADING',
  GET_GROUPS_FAILURE: 'GET_GROUPS_FAILURE',
}
 
export default actionTypes;