const actionTypes = {
  GET_GROUP_CHAT_SUCCESS: 'GET_GROUP_CHAT_SUCCESS',
  GET_GROUPS_SUCCESS: 'GET_GROUPS_SUCCESS',
  GET_GROUPS_LOADING: 'GET_GROUPS_LOADING',
  GET_GROUPS_FAILURE: 'GET_GROUPS_FAILURE',
  GROUP_MESSAGE_SENT: 'GROUP_MESSAGE_SENT',
  SEND_GROUP_MESSAGE_FAILURE: 'SEND_GROUP_MESSAGE_FAILURE',
  LOAD_MORE_GROUP_CHAT: 'LOAD_MORE_GROUP_CHAT'
}
 
export default actionTypes;